### ISSUE TITLE
AH initial review + add content to Handbook

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/equity-data-handbook#27]
Review, streamline, add content to each page of the Handbook

- [x] Convert to Quarto site (according to [Issue](https://github.com/CAWaterBoardDataCenter/equity-data-handbook/issues/6))
    - [x] Create image sub-folders within each section folder, move images accordingly
- [x] Welcome
- [x] Background
- [x] Getting Started
    - [x] Best Practices < to be deleted
    - [x] Establishing Common Language
- [x] Publish Your Data (See [Issue](https://github.com/CAWaterBoardDataCenter/equity-data-handbook/issues/37) for more details)
- [x] Plan & Prepare
    - [x] Planning
    - [x] Data Preparation
- [x] Collect & Process
    - [x] Data Sources (maybe rename to Data Collection and have Data Sources & Data Limitations sections?)
    - [x] Data Collection
    - [x] Surveys (merged with data collection page)
    - [x] Data Limitation (merge with data sources on to be created Data Collection page?)
    - [x] Data Processing (create page and go over tidying with an equity lens)
- [x] Assure & Analyze
    - [x] Quality Assurance
    - [x] Data Analysis
    - [x] Data Visualization
    - [x] Demographics Data (merged with data collection page)
    - [x] CalEnviroScreen (merged with data collection page)
- [x] Preserve & Store
- [x] Publish & Share
- [x] Discover & Integrate (aka process Evaluation)
- [x] Describe (aka Documentation)
- [x] Use Cases
    - [x] SWAMP (See [Issue](https://github.com/CAWaterBoardDataCenter/equity-data-handbook/issues/29) for more details)
    - [ ] Demographics Data (Reminder for me to schedule meeting with HG via calendly as soon as I begin work on this page)
- [x] Resources (if page is getting too long - consider creating a resource section and adding pages for each resource type)
- [x] Inspiration
